;;; popup-kill-ring-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from popup-kill-ring.el

(autoload 'popup-kill-ring "popup-kill-ring" "\
Interactively insert selected item from `key-ring' by `popup.el'
and `pos-tip.el'" t)
(register-definition-prefixes "popup-kill-ring" '("popup-kill-ring"))

;;; End of scraped data

(provide 'popup-kill-ring-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; popup-kill-ring-autoloads.el ends here
