[main]
# Update this path to match where 'ninja install' put the file
modules=/usr/local/lib/x86_64-linux-gnu/gtklock/runshell-module.so

[runshell]
command=/home/trang/.config/gtklock/battery.sh
refresh=60
runshell-position=top-right
