# This contains only GUI settings for GRC and is not meant for users to edit.
#
# GRC settings not accessible through the GUI are in config.conf under
# section [grc].

[main]
variable_editor_visable = False
xterm_missing = x-terminal-emulator
file_open = 
main_window_width = 905
main_window_height = 731
console_window_position = 530
blocks_window_position = 775
variable_editor_position = 284

[files_recent]

[files_open]

